//list of all factulties
export const faculties = [
  { label: "Droit", value: "Droit" },
  { label: "Economie", value: "Economie" },
  { label: "Gestion", value: "Gestion" },
  { label: "Communication", value: "Communication" },
  { label: "Marketing", value: "Marketing" },
  { label: "Psychologie", value: "Psychologie" },
  { label: "Lettres et langues", value: "Lettres et langues" },
  { label: "Arts et Sciences humaines", value: "Arts et Sciences humaines" },
  { label: "Sciences et technologies", value: "Sciences et technologies" },
  { label: "Informatique", value: "Informatique" },
  { label: "Science politique", value: "Science politique" },
  {
    label: "Sciences de la vie et de la terre",
    value: "Sciences de la vie et de la terre",
  },
  { label: "Physique", value: "Physique" },
  { label: "Philosophie", value: "Philosophie" },
  { label: "Mécanique", value: "Mécanique" },
  { label: "Sciences du langage", value: "Sciences du langage" },
  { label: "Mathématiques", value: "Mathématiques" },
  { label: "Géographie", value: "Géographie" },
  { label: "Chimie", value: "Chimie" },
  { label: "Sciences de l'éducation", value: "Sciences de l'éducation" },
  {
    label: "Science de la terre et de l'univers",
    value: "Science de la terre et de l'univers",
  },
  { label: "Sciences de la matières", value: "Sciences de la matières" },
];

export const faculties = [
  "PERFORMING_ARTS",
  "PLASTIC_ARTS",
  "CULTURAL_STUDIES",
  "HEALTH_AND_SOCIAL_SIENCES",
  "THEOLOGY",
  "SOCIOLOGY",
  "HUMAN_SCIENCES",
  "HEALTH_SCIENCES",
  "ENGENEERING_SIENCES",
  "SPORT_SCIENCES",
  "BIOLOGY",
  "MATH_HUMAN_SCIENCES",
  "ELECTRONICS",
  "CIVIL_ENGENEERING",
  "MUSICOLOGY",
  "ARCHITECTURE",
  "PHARMACY",
  "DENTISTRY",
  "MEDECINE",
  "MIDWIFE",
  "ECONOMY_MANAGMENT",
  "STORY",
  "ARCHEOLOGY_STORY",
  "ECONOMIC_SOCIAL_ADMINISTRATION",
  "FOREIGN_LANGUAGES",
  "INFORMATION_AND_COMMUNICATION",
  "CLASSICAL_LETTERS",
  "PUBLIC_ADMINISTRATION",
  "LETTERS_REGIONAL_CULTURES",
  "MODERN_LETTERS",
  "MATERIAL_SCIENCES",
];
